// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config'

import 'dotenv/config'

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations'
  },
  // During migrations use DIRECT_URL. Migration can stuck on DATABASE_URL. I haven't found a solution for this problem :(
  datasource: {
    url: process.env['DIRECT_URL']
  }
})
